const HEADER_LINES = [
  '#!/bin/sh',
  'PATH=/sbin:/bin:/usr/sbin:/usr/bin',
  '',
  '# LIVI helper CGI',
  '',
  'header() {',
  '  printf "Content-type: text/html\\r\\n\\r\\n"',
  '  echo "<!DOCTYPE html>"',
  '  echo "<html><head><meta charset=\\"utf-8\\"><title>LIVI tools</title>"',
  '  echo "<meta name=\\"viewport\\" content=\\"width=device-width, initial-scale=1\\">"',
  '  echo "<style>',
  '    body{font-family:system-ui,Arial,sans-serif;background:#111;color:#eee;padding:16px;margin:0;}',
  '    .wrap{max-width:980px;margin:0 auto;}',
  '    h1{font-size:18px;margin:0 0 10px;} h2{font-size:14px;margin:16px 0 8px;}',
  '    a{color:#0bf;text-decoration:none;} a:hover{text-decoration:underline;}',
  '    .bar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:8px 0 12px;}',
  '    .chip{display:inline-block;background:#1b1b1b;border:1px solid #2a2a2a;padding:4px 8px;border-radius:8px;}',
  '    .muted{color:#aaa;}',
  '    pre{background:#222;padding:10px;border-radius:10px;white-space:pre-wrap;overflow-x:auto;}',
  '    code{background:#222;padding:2px 4px;border-radius:6px;}',
  '    ul{list-style:none;padding:0;margin:0;}',
  '    li{padding:6px 0;border-bottom:1px solid #1f1f1f;}',
  '    .row{display:flex;justify-content:space-between;gap:12px;align-items:baseline;}',
  '    .name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:75vw;}',
  '    .kind{color:#aaa;font-size:12px;}',
  '    .actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end;}',
  '    .btn{display:inline-block;background:#1b1b1b;border:1px solid #2a2a2a;padding:4px 8px;border-radius:8px;}',
  '    .btn:hover{border-color:#555;}',
  '  </style>"',
  '  echo "</head><body><div class=\\"wrap\\">"',
  '}',
  '',
  'footer() {',
  '  echo "</div></body></html>"',
  '}',
  '',
  'header_plain() {',
  '  printf "Content-type: text/plain\\r\\n\\r\\n"',
  '}',
  '',
  'header_bin() {',
  '  file="$1"',
  '  name="$(basename "$file")"',
  '  printf "Content-Type: application/octet-stream\\r\\n"',
  '  printf "Content-Disposition: attachment; filename=\\"%s\\"\\r\\n" "$name"',
  '  printf "Content-Transfer-Encoding: binary\\r\\n\\r\\n"',
  '}',
  '',
  'download_file() {',
  '  path="$1"',
  '  if [ -z "$path" ] || [ ! -f "$path" ]; then',
  '    header_plain',
  '    echo "Not a file."',
  '    return',
  '  fi',
  '  header_bin "$path"',
  '  dd if="$path" bs=4096 2>/dev/null',
  '}',
  '',
  'b64_file() {',
  '  path="$1"',
  '  if [ -z "$path" ] || [ ! -f "$path" ]; then',
  '    header_plain',
  '    echo "Not a file."',
  '    return',
  '  fi',
  '  printf "Content-Type: text/plain\\r\\n"',
  '  printf "Content-Disposition: attachment; filename=\\"%s.b64\\"\\r\\n\\r\\n" "$(basename "$path")"',
  '  base64 "$path"',
  '}',
  '',
  'nav() {',
  '  echo "<div class=\\"bar\\">"',
  '  echo "<span class=\\"chip\\"><a href=\\"/\\">Home</a></span>"',
  '  echo "</div>"',
  '}',
  '',
  'htmlesc() {',
  "  printf '%s' \"$1\" | sed 's/&/\\&amp;/g;s/</\\&lt;/g;s/>/\\&gt;/g;s/\"/\\&quot;/g'",
  '}',
  '',
  'urldec_path() {',
  "  printf '%s' \"$1\" | sed 's/+/ /g;s/%2F/\\//g;s/%20/ /g;s/%25/%/g'",
  '}',
  '',
  'urldec_cmd() {',
  "  printf '%s' \"$1\" | sed 's/+/ /g;s/%20/ /g;s/%21/!/g;s/%22/\"/g;s/%23/#/g;s/%24/\\$/g;s/%26/\\&/g;s/%27/'\"'\"'/g;s/%28/(/g;s/%29/)/g;s/%2A/*/g;s/%2B/+/g;s/%2C/,/g;s/%2D/-/g;s/%2E/./g;s/%2F/\\//g;s/%3A/:/g;s/%3B/;/g;s/%3C/</g;s/%3D/=/g;s/%3E/>/g;s/%3F/?/g;s/%40/@/g;s/%5B/\\[/g;s/%5C/\\\\/g;s/%5D/\\]/g;s/%5E/\\^/g;s/%5F/_/g;s/%60/`/g;s/%7B/{/g;s/%7C/|/g;s/%7D/}/g;s/%7E/~/g;s/%25/%/g'",
  '}',
  '',
  'urlenc() {',
  "  printf '%s' \"$1\" | sed 's/%/%25/g;s/ /%20/g;s/#/%23/g;s/?/%3F/g;s/&/%26/g'",
  '}',
  ''
]

const ACTION_LINES = [
  'run_exec() {',
  '  if [ "$raw" = "1" ]; then',
  '    header_plain',
  '  else',
  '    header',
  '    nav',
  '    echo "<h1>Exec</h1>"',
  '    echo "<p class=\\"muted\\">Output below. Use raw=1 for text/plain.</p>"',
  '    echo "<pre>"',
  '  fi',
  '',
  '  c="$cmd"',
  '  if [ -z "$c" ]; then',
  '    echo "No cmd provided. Use ?action=exec&raw=1&cmd=..."',
  '    [ "$raw" = "1" ] || { echo "</pre>"; footer; }',
  '    return',
  '  fi',
  '',
  '  case "$c" in',
  '    *"rm -rf /"*|*"rm -rf/"*|*"mkfs"*|*"flash"*|*"ubiformat"*|*"nandwrite"*|*"mtd"*)',
  '      echo "Blocked command."',
  '      echo ""',
  '      echo "$c"',
  '      [ "$raw" = "1" ] || { echo "</pre>"; footer; }',
  '      return ;;',
  '  esac',
  '',
  '  CAP=200000',
  '  sh -lc "$c" 2>&1 | head -c "$CAP"',
  '',
  '  [ "$raw" = "1" ] || { echo "</pre>"; footer; }',
  '}',
  '',
  'view_file() {',
  '  header',
  '  path="$1"',
  '  [ -z "$path" ] && path="/"',
  '  title=$(htmlesc "$path")',
  '  echo "<h1>View $title</h1>"',
  '  nav',
  '  echo "<div class=\\"bar\\">"',
  '  echo "<span class=\\"chip\\"><a href=\\"$SCRIPT_NAME?action=download&amp;path=$(urlenc "$path")\\">Download binary</a></span>"',
  '  echo "<span class=\\"chip\\"><a href=\\"$SCRIPT_NAME?action=b64&amp;path=$(urlenc "$path")\\">Download base64</a></span>"',
  '  echo "</div>"',
  '',
  '  if [ ! -f "$path" ]; then',
  '    echo "<p>Not a file.</p>"',
  '    footer',
  '    return',
  '  fi',
  '',
  '  echo "<h2>Stat</h2><pre>"',
  '  ls -l "$path" 2>&1',
  '  echo "</pre>"',
  '',
  '  echo "<h2>Text</h2><pre>"',
  '  head -c 12000 "$path" 2>&1',
  '  echo "</pre>"',
  '',
  '  echo "<h2>Binary dump</h2><pre>"',
  '  od "$path" 2>/dev/null | head -200',
  '  echo "</pre>"',
  '',
  '  footer',
  '}',
  '',
  'browse() {',
  '  header',
  '  path="$1"',
  '  [ -z "$path" ] && path="/"',
  '',
  '  if [ ! -d "$path" ]; then',
  '    echo "<p>Not a directory.</p>"',
  '    footer',
  '    return',
  '  fi',
  '',
  '  echo "<h1>Browse $(htmlesc "$path")</h1>"',
  '  nav',
  '',
  '  parent=$(dirname "$path")',
  '  if [ "$path" != "/" ]; then',
  '    echo "<div class=\\"bar\\">"',
  '    echo "<span class=\\"chip\\"><a href=\\"$SCRIPT_NAME?action=ls&amp;path=$(urlenc "$parent")\\">⬆ Parent</a></span>"',
  '    echo "</div>"',
  '  fi',
  '',
  '  echo "<ul>"',
  '  for e in "$path"/* "$path"/.*; do',
  '    [ -e "$e" ] || continue',
  '    case "$e" in //*) e="/${e#//}" ;; esac',
  '    b="$(basename "$e")"',
  '    [ "$b" = "." ] || [ "$b" = ".." ] && continue',
  '    enc=$(urlenc "$e")',
  '',
  '    if [ -d "$e" ]; then',
  '      echo "<li><div class=\\"row\\"><div class=\\"name\\"><a href=\\"$SCRIPT_NAME?action=ls&amp;path=$enc\\">$b/</a></div><div class=\\"kind\\">dir</div></div></li>"',
  '    elif [ -f "$e" ]; then',
  '      size=$(ls -l "$e" 2>/dev/null | awk "{print \\$5}")',
  '      [ -z "$size" ] && size="?"',
  '      echo "<li>"',
  '      echo "<div class=\\"row\\">"',
  '      echo "<div class=\\"name\\">$b <span class=\\"kind\\">($size bytes)</span></div>"',
  '      echo "<div class=\\"actions\\">"',
  '      echo "<a class=\\"btn\\" href=\\"$SCRIPT_NAME?action=view&amp;path=$enc\\">View</a>"',
  '      echo "<a class=\\"btn\\" href=\\"$SCRIPT_NAME?action=download&amp;path=$enc\\">Download</a>"',
  '      echo "<a class=\\"btn\\" href=\\"$SCRIPT_NAME?action=b64&amp;path=$enc\\">Base64</a>"',
  '      echo "</div>"',
  '      echo "</div>"',
  '      echo "</li>"',
  '    fi',
  '  done',
  '',
  '  echo "</ul>"',
  '  footer',
  '}',
  ''
]

const ROUTER_LINES = [
  'qs="$QUERY_STRING"',
  'action=""',
  'path=""',
  'cmd=""',
  'raw=""',
  '',
  'case "$qs" in *action=*) action=${qs#*action=}; action=${action%%&*} ;; esac',
  'case "$qs" in *path=*) path=${qs#*path=}; path=${path%%&*}; path=$(urldec_path "$path") ;; esac',
  'case "$qs" in *cmd=*) cmd=${qs#*cmd=}; cmd=${cmd%%&*}; cmd=$(urldec_cmd "$cmd") ;; esac',
  'case "$qs" in *raw=*) raw=${qs#*raw=}; raw=${raw%%&*} ;; esac',
  '',
  'case "$action" in',
  '  exec)     run_exec ;;',
  '  ls)       browse "$path" ;;',
  '  view)     view_file "$path" ;;',
  '  download) download_file "$path" ;;',
  '  b64)      b64_file "$path" ;;',
  'esac',
  ''
]

export const buildServerCgiScript = (): string =>
  [...HEADER_LINES, ...ACTION_LINES, ...ROUTER_LINES].join('\n')
